const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Nike Slim pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 25,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Puma Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Nike",
      rating: 4,
      numReviews: 4,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 100,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 13,
      description: "high quality product",
    },
  ],
};

export default data;
